### ISSUE TITLE
Add icons for specific folders

### ISSUE THREAD

**Issue by cadamsdev** [cadamsdev/vscode-jetbrains-icon-theme#37]
e.g for folders named "resources"

We could use icon
![resourcesRoot](https://user-images.githubusercontent.com/12568665/168404628-53d1d77c-040f-4882-be51-ce4f4b982592.svg)

This feature should be toggleable.

**Comment by reekystive** [comment]
Personally I don't like assigning icons for specific folders (e.g. `types`, `resources`, `images`, `assets`) because they can be inaccurate, appear in all types of projects, and will be __annoying__. Sometimes my `resources` folder is just resource-related code, not resource files. Also `types` folder is only valid for some specific projects (e.g. TypeScript).

For reference, JetBrains IDEs never simply assign icons by folder names. I think this is something that needs serious consideration. :D

**Comment by reekystive** [comment]
Also, unlike file extensions, .ts must (probably) be a TypeScript file, and .png must be an image file, but there's nothing that says that files in the resources folder must be resource files.

So I think what a folder is used for depends on the user's own intent, so it requires the user to specify a folder to be used for a specific purpose themselves, rather than simply assigning icons based on the filename. Like "Mark Directory As" in JetBrains' IDE:

<img width="502" alt="Screenshot 2023-09-01 at 14 18 33" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/26853900/a0447697-70d5-4b95-8898-43d9eca5ea0b">

**Comment by LucausMartin** [comment]
Maybe two solutions can be made, one is to not distinguish folders with special meanings, and the other is to distinguish

**Comment by cadamsdev** [comment]
Closing this issue for now to keep the icon set simple.
